# Generated by Django 6.0.1 on 2026-03-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sovrinlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qita', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='kamanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nomer', models.IntegerField()),
                ('murabbiy', models.CharField(max_length=200)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.liga')),
            ],
        ),
        migrations.CreateModel(
            name='oyincilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nomer', models.IntegerField()),
                ('gollar', models.IntegerField()),
                ('asiste', models.IntegerField()),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.davlat')),
                ('kamanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.kamanda')),
            ],
        ),
        migrations.CreateModel(
            name='pazitsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('oyincilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.oyincilar')),
            ],
        ),
    ]
