# Generated by Django 6.0.1 on 2026-03-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamanda',
            name='nomer',
        ),
        migrations.AddField(
            model_name='kamanda',
            name='sovrinlar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liga.sovrinlar'),
            preserve_default=False,
        ),
    ]
