# Generated by Django 6.0.1 on 2026-03-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_remove_kamanda_nomer_kamanda_sovrinlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamanda',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kamanda',
            name='logo',
            field=models.ImageField(default=1, upload_to='kamanda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kamanda',
            name='ochko',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kamanda',
            name='stadion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kamanda',
            name='tashkil_topgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oyincilar',
            name='boyi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oyincilar',
            name='rasmi',
            field=models.ImageField(default=1, upload_to='oyincilar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oyincilar',
            name='vazni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sovrinlar',
            name='haqida',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sovrinlar',
            name='rasmi',
            field=models.ImageField(default=1, upload_to='sovrinlar'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bozor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liga.oyincilar')),
            ],
        ),
    ]
