# Generated by Django 6.0.1 on 2026-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_kamanda_city_kamanda_logo_kamanda_ochko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamanda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kamanda'),
        ),
        migrations.AlterField(
            model_name='oyincilar',
            name='rasmi',
            field=models.ImageField(blank=True, null=True, upload_to='oyincilar'),
        ),
        migrations.AlterField(
            model_name='sovrinlar',
            name='rasmi',
            field=models.ImageField(blank=True, null=True, upload_to='sovrinlar'),
        ),
    ]
