# Generated by Django 6.0.1 on 2026-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_alter_kamanda_logo_alter_oyincilar_rasmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bozor',
            name='narxi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
